In [3]:
#Importing libraries
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Website-data/master/supplement.csv")
dataset

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday Discount  #Order     Sales  
0             1      Yes       9   7011.84  
1             1      Yes      60  51789.12  
2             1      Yes      42  36868.20  
3             1      Yes      23  19715.16  
4             1      Yes      62  45614.52  
...         ...      ...     ...       ...  
188335        1      Yes      51  37272.00  
188336        1       No      90  54572.64  
188337        1       No      56  31624.56  
188338        1      Yes      70  49162.41  
188339        1       No      47  37977.00  

[188340 rows x 10 columns]

In [5]:
dataset.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [6]:
import plotly.express as px

In [7]:
pie = dataset["Store_Type"].value_counts()
store = pie.index
orders = pie.values
fig = px.pie(dataset , values=orders , names = store)
fig.show()

In [8]:
pie = dataset["Location_Type"].value_counts()
location = pie.index
orders = pie.values
fig = px.pie(dataset , values=orders , names = location)
fig.show()

In [9]:
pie = dataset["Region_Code"].value_counts()
region = pie.index
orders = pie.values
fig = px.pie(dataset , values=orders , names = region)
fig.show()

In [10]:

pie = dataset["Discount"].value_counts()
discount = pie.index
orders = pie.values
fig = px.pie(dataset , values=orders , names = discount)
fig.show()

In [11]:
dataset["Discount"] = dataset["Discount"].map({"Yes":1 , "No":0})
dataset

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1         1       9   7011.84  
1             1         1      60  51789.12  
2             1         1      42  36868.20  
3             1         1      23  19715.16  
4             1         1      62  45614.52  
...         ...       ...     ...       ...  
188335        1         1      51  37272.00  
188336        1         0      90  54572.64  
188337        1         0      56  31624.56  
188338        1         1      70  49162.41  
188339        1         0      47  37977.00  

[188340 rows x 10 columns]

In [12]:
dataset["Store_Type"] = dataset["Store_Type"].map({"S1":1 ,"S2":2,"S3":3,"S4":4})
dataset

ID  Store_id  Store_Type Location_Type Region_Code        Date  \
0       T1000001         1           1            L3          R1  2018-01-01   
1       T1000002       253           4            L2          R1  2018-01-01   
2       T1000003       252           3            L2          R1  2018-01-01   
3       T1000004       251           2            L3          R1  2018-01-01   
4       T1000005       250           2            L3          R4  2018-01-01   
...          ...       ...         ...           ...         ...         ...   
188335  T1188336       149           2            L3          R2  2019-05-31   
188336  T1188337       153           4            L2          R1  2019-05-31   
188337  T1188338       154           1            L3          R2  2019-05-31   
188338  T1188339       155           3            L1          R2  2019-05-31   
188339  T1188340       152           2            L1          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1         1       9   7011.84  
1             1         1      60  51789.12  
2             1         1      42  36868.20  
3             1         1      23  19715.16  
4             1         1      62  45614.52  
...         ...       ...     ...       ...  
188335        1         1      51  37272.00  
188336        1         0      90  54572.64  
188337        1         0      56  31624.56  
188338        1         1      70  49162.41  
188339        1         0      47  37977.00  

[188340 rows x 10 columns]

In [13]:
dataset["Location_Type"] = dataset["Location_Type"].map({"L1":1 ,"L2":2,"L3":3,"L4":4,"L5":5})
dataset

ID  Store_id  Store_Type  Location_Type Region_Code        Date  \
0       T1000001         1           1              3          R1  2018-01-01   
1       T1000002       253           4              2          R1  2018-01-01   
2       T1000003       252           3              2          R1  2018-01-01   
3       T1000004       251           2              3          R1  2018-01-01   
4       T1000005       250           2              3          R4  2018-01-01   
...          ...       ...         ...            ...         ...         ...   
188335  T1188336       149           2              3          R2  2019-05-31   
188336  T1188337       153           4              2          R1  2019-05-31   
188337  T1188338       154           1              3          R2  2019-05-31   
188338  T1188339       155           3              1          R2  2019-05-31   
188339  T1188340       152           2              1          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1         1       9   7011.84  
1             1         1      60  51789.12  
2             1         1      42  36868.20  
3             1         1      23  19715.16  
4             1         1      62  45614.52  
...         ...       ...     ...       ...  
188335        1         1      51  37272.00  
188336        1         0      90  54572.64  
188337        1         0      56  31624.56  
188338        1         1      70  49162.41  
188339        1         0      47  37977.00  

[188340 rows x 10 columns]

In [14]:
x = np.array(dataset[["Store_Type","Location_Type","Holiday","Discount"]])
y = np.array(dataset["#Order"])

In [15]:
x

array([[1, 3, 1, 1],
       [4, 2, 1, 1],
       [3, 2, 1, 1],
       ...,
       [1, 3, 1, 0],
       [3, 1, 1, 1],
       [2, 1, 1, 0]])

In [16]:
y

array([ 9, 60, 42, ..., 56, 70, 47])

In [17]:
#Building the ML Model
from sklearn.model_selection import train_test_split as tts

In [21]:
x_train, x_test, y_train, y_test = tts(x,y,test_size=0.2,random_state=42)

In [22]:
x_train

array([[2, 3, 0, 0],
       [3, 1, 0, 0],
       [4, 1, 0, 0],
       ...,
       [1, 1, 0, 1],
       [1, 3, 0, 1],
       [2, 4, 0, 0]])

In [23]:
#importing the model that we are going to implement
import lightgbm as ltb
model = ltb.LGBMRegressor()

In [25]:
#passing our test set inside the model
model.fit(x_train,y_train)

LGBMRegressor()

In [26]:
y_pred = model.predict(x_test)

In [27]:
y_pred

array([47.35189701, 97.06871721, 66.57778822, ..., 47.35189701,
       61.74938636, 85.34103853])

In [28]:
y_test

array([ 54, 111,  59, ...,  40,  69,  68])

In [29]:
data = pd.DataFrame(data={"Predicted Orders " :y_pred.flatten()})

In [30]:
data

Predicted Orders 
0              47.351897
1              97.068717
2              66.577788
3              85.143083
4              54.451098
...                  ...
37663          66.577788
37664          47.722874
37665          47.351897
37666          61.749386
37667          85.341039

[37668 rows x 1 columns]